
# Implementing Authentication and Authorization

## Authentication 
### Custom 

### Third party 

## Authorization 

## JSON Web Tokens (JWT)

"JSON Web Tokens are an open, industry standard RFC 7519 method for representing claims securely between two parties." (jwt.io)

The JWT stratgey allows to use JSON Web Tokens (JWT) to secure your plumber endpoints. A great introduction to JWT can be found [here](https://jwt.io/introduction/). JWT can be used to secure REST APIs without sessions. They are considered to be stateless although they can also be used as stateful session tokens. 


JSON Web Tokens (JWT) *can* contain claims. "Claims are statements about an entity (typically, the user) and additional data" ([https://jwt.io/introduction/](https://jwt.io/introduction/)). They are expressed as key-value pairs.

There are three different types of claims: registered, public and private claims. All types of claims are implemented in the same manner, they only differ in whether and where the claims are registered with the Internet Assigned Numbers Authority (IANA). For example, the `iss` claim is a registered claim defined in the JWT standard [RFC 7519](https://tools.ietf.org/html/rfc7519#page-8) and registered at IANA. See the [JWT Introduction](https://jwt.io/introduction/) of [jwt.io](jwt.io) for more details.


`sealr` allows you to check for the validity of all types of claims in a given JWT using the `claims` argument of the `sealr::is_authed_jwt` function. 
